{% set name = "datacache" %}
{% set version = "1.2.1" %}
{% set sha256 = "ed24c419ed9791ef0f0375ca5552b2300922235ee9ffa81d200f002c6f7d7955" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - pandas >=0.15.2
    - appdirs >=1.4.0
    - progressbar33 >=2.4
    - biopython >=1.65
    - requests >=2.5.1
    - typechecks >=0.0.2
    - mock

test:
  imports:
    - datacache

about:
  home: https://github.com/openvax/datacache
  license: Apache-2.0
  license_family: Apache
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Helpers for transparently downloading datasets

extra:
  recipe-maintainers:
    - npavlovikj
