{% set name = "datacache" %}
{% set version = "1.1.0" %}
{% set sha256 = "4d22c9d5e045739519a25b5e5ed845df76bdb29ce081a00dcda00b5c8fcb3fdf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - setuptools
  run:
    - python
    - pandas >=0.15.2
    - appdirs >=1.4.0
    - progressbar33 >=2.4
    - biopython >=1.65
    - requests >=2.5.1
    - typechecks >=0.0.2
    - mock

test:
  imports:
    - datacache

about:
  home: https://github.com/openvax/datacache
  license: Apache-2.0
  license_family: Apache
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Helpers for transparently downloading datasets'

extra:
  recipe-maintainers:
    - npavlovikj
