travis:
  secure:
    BINSTAR_TOKEN: gaJ/ODhHGycm+Tr4jbmenJk6RP6E1mNB497derDZi465uh8ASy47CPB5IP04ntnlvjwxw8SSmLbjp5nmVRkNaR8D5BtdbcFQdyBBxsIbBB/lnSHrMueDsAiUYQMLrJJanD9V4V3zzLavCS0FMDsEDNQrt1HRVasISlII2cNFgL8kFpwLz/UQigBPy6CzNPjqeV7Svd7Jq3iUcMVIMSnLAVs8zM9SDYr/VF5zeKunLMt+OluTnY37QbveMfE8Cnn5DAg5BfwhYaduNsl7vPiFNRwtB+EPkS8f36AWZJV4+KARs2Icz80PkbVDmUgbK7WVc2hN55zZZonUhPSdXUfVzwxPf6Ke5wFbjIOsHikQ/zFe9iwHXG3r/iCYI9yC0r+6USVbQHRNVPXDjEt1jM12wSUv5XmQi+DHZZBZAZe6JdGsn0gQ6WXpP0sAem09F4uOhcsYXlwdPhDFqOIvaTZCQxfHrmBDIIU/OhJiL3frEgi6QK5jdId68xBERzV7vhlNhSxbVPWdAHP2pC/ctkFE4YKN66TzR2Wxf+gnWXtRQkwxQVAa4fO4jyYgxTps+wk+eEv0Y44CsN59pU7RiE0oVliStvpPAn6C9K/iNbi2SiL5ppPDRihMALeh3v5tmgKbC0EbksFFJmUu3NDetyDxGF9Z1ViWklQULxU0ZWWHoGc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
