travis:
  secure:
    BINSTAR_TOKEN: DtJI0w+ru0/uZnl5wdE5QuluDpT5JKgs3RVsn7drKsf0X9pkTwTTdIZhR/BziejkUC9tqB5/0ZwHm4rZEDL6BNFz39uMTjgYeBBfwR3tnyc1d+j0BHCNYzrofJaWseGYI5l++24CIjwLuYLkJQe5tSbDTpzVfpDHbFhtkJgPpBudTH9zHE57e9gA3z7RjCu6fCLOorMFWeQIkjVNg1Cht2A+Gd0b6NYZAR6bXUEoHmPXtfyfjpPUb0FMF/OtwHrANc1DopbBQpuHy7GYBmwxmUmkjwFRu0yi+xnjY98+6gGKTlZTF0UuMWNDzplCWiYxMj8i37J6BLYtALUHyrdfzyxpZaa2+QahOzVUIrUr6agC/5AM5x8mGUkWb3NS8m8pfoLJsXYqWCwuijnn2t0I1ZB9gcthQmChRBph5TbPnL2lmFCj1bF39XNJXz3LbN1+CUFyg/Ac9CtSG9mCwneYbuyrzDKfhNvWPPLfdFp+cIzizgLOYaCwg//QWiO0/NhtLlZ2WIWRiYc+iyC2B4q11nQV76arUE+eZNa1+08PAnTjtVvFOzXDpy4IwmVb/0L7OtKIsdxMX+rDcNqwKRIgSzrROalinv0YiA0vUBx2ZanQX8JSMacCvhjp2TTuWEAO9dZzpJ3qAmGxyrBAiCktJMiURGB4y5/zZUXiKk0fsf0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
